name: SonarCloud
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest
    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
         dotnet-version: '8.0.x'     
      - name: Build  
        shell: powershell
        run: |          
          dotnet build          
